### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by mandynicole5** [fstenstrom/world-boss-timers#110] opened 2024-02-10 02:30 UTC
/wbt stopped working for me earlier today, not able to view or share timers, uninstalling and reinstalling did not work, reloading did not work

**Comment by fstenstrom** [comment] 2024-04-14 09:38
I'd probably need stacktrace (e.g. from Bugsack+Buggrabber) to understand this. Could also be interface mismatch. Closing for now since it's been a while. If you have stacktrace please reopen.

**Closed by fstenstrom** 2024-04-14 09:38 UTC

**Comment by fstenstrom** [comment] 2024-04-14 10:19
This could be caused by #109
