### ISSUE TITLE
Share button not doing anything

### ISSUE THREAD

**Issue by ohmaidayz** [fstenstrom/world-boss-timers#51] opened 2021-03-18 09:18 UTC
Can't seem to share my info, when hitting the button nothing happens anymore. Likely to be clashing with another addon or human error on my part?

**Comment by fstenstrom** [comment] 2021-03-20 10:56
Could be issue in WBT as well. I did change some conditions for allowing to share.

Could you provide the conditions for when it doesn't work?
- Realm name
- EU/NA/other
- Are you using latest version of addon?

**Comment by Randolini** [comment] 2021-04-12 13:16
I have the same problem. 

Magtheridon 
EU
Just installed the latest version. I can Req. but not Share timers. If I request and others share, I get the timers into my list, but when I click Share - nothing happens.

**Comment by wbtuser** [comment] 2021-05-14 04:54
Same exact issue here.  I can use the /wbt button to look at options, i can use the req button to ask for someone to share data, but my share button does nothing when i hit it.

**Comment by fstenstrom** [comment] 2021-05-14 08:42
I plan to add some debug logging that can be toggled on/off for this, since there are many conditions that may cause this to happen. I suspect it has to do with multiple bosses in the same zone (example Kunlai, since Zandalari Warbringers are also tracked), or it has to do with the new conditions to allow sharing across connected realms.

If it only happens in certain zones, or if it's everywhere, please comment it here.

**Comment by fstenstrom** [comment] 2021-05-16 15:18
Latest version (v1.9) now prints Info messages by default when unable to share. If anyone still has this issue please let me know what messages you are getting.

**Comment by wbtuser** [comment] 2021-05-19 17:49
Happening in all zones for all bosses.  Example of the new text I get when I try to share Rukhmar timer:

WBT: [Info]: Cannot share timer for Rukhmar:
WBT: [Info]: Player was in a group during previous kill.

**Comment by fstenstrom** [comment] 2021-05-19 18:52
> Happening in all zones for all bosses. Example of the new text I get when I try to share Rukhmar timer:
> 
> WBT: [Info]: Cannot share timer for Rukhmar:
> WBT: [Info]: Player was in a group during previous kill.

Thanks for sharing.

Is the content of the message correct, i.e. were you in a group when you Rukhmar was killed or you received the timer?

**Comment by wbtuser** [comment] 2021-05-19 19:11
Yes I was in a group, flying towards Rukhmar when he died.  I didnt hit him so I still needed to wait the 15 minutes.

**Comment by fstenstrom** [comment] 2021-05-22 08:37
Closing for now since most likely not a bug.

**Closed by fstenstrom** 2021-05-22 08:37 UTC
Labels: bug
