### ISSUE TITLE
Bug: Incompatible with Macro Manager

### ISSUE THREAD

**Issue by nancikennedy** [fstenstrom/world-boss-timers#82] opened 2022-11-18 13:06 UTC
On Retail, with the latest versions of MM and WBT installed, clicking on the MM window to move it causes WBT to throw an error.

2x WorldBossTimers/GUI.lua:395: attempt to index field 'window' (a nil value)
[string "@WorldBossTimers/GUI.lua"]:395: in function <WorldBossTimers/GUI.lua:394>

Locals:
this = Button {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'window' (a nil value)"
self = <table> {
 released = true
 Rebuild = <function> defined @WorldBossTimers/GUI.lua:169
 UpdateContent = <function> defined @WorldBossTimers/GUI.lua:214
 UpdateWidth = <function> defined @WorldBossTimers/GUI.lua:139
 CyclicLabelResetTrigger = <function> defined @WorldBossTimers/GUI.lua:199
 RemoveLabel = <function> defined @WorldBossTimers/GUI.lua:162
 Restart = <function> defined @WorldBossTimers/GUI.lua:45
 InitPosition = <function> defined @WorldBossTimers/GUI.lua:275
 Show = <function> defined @WorldBossTimers/GUI.lua:75
 UpdatePosition = <function> defined @WorldBossTimers/GUI.lua:259
 NewBasicWindow = <function> defined @WorldBossTimers/GUI.lua:322
 height = 106
 ShouldHide = <function> defined @WorldBossTimers/GUI.lua:65
 SetupAceGUI = <function> defined @WorldBossTimers/GUI.lua:306
 btn_req = <table> {
 }
 Update = <function> defined @WorldBossTimers/GUI.lua:248
 ShouldShow = <function> defined @WorldBossTimers/GUI.lua:53
 btn_container = <table> {
 }
 SaveGuiPoint = <function> defined @WorldBossTimers/GUI.lua:286
 CreateNewLabel = <function> defined @WorldBossTimers/GUI.lua:112
 CreateLabels = <function> defined @WorldBossTimers/GUI.lua:41
 btn_share = <table> {
 }
 RecordPositioning = <function> defined @WorldBossTimers/GUI.lua:297
 LabelWidth = <function> defined @WorldBossTimers/GUI.lua:108
 visible = false
 width = 200
 Init = <function> defined @WorldBossTimers/GUI.lua:37
 AceGUI = <table> {
 }
 ResetPosition = <function> defined @WorldBossTimers/GUI.lua:301
 New = <function> defined @WorldBossTimers/GUI.lua:345
 LockOrUnlock = <function> defined @WorldBossTimers/GUI.lua:101
 UpdateHeight = <function> defined @WorldBossTimers/GUI.lua:128
 CleanUpWidgetsAndRelease = <function> defined @WorldBossTimers/GUI.lua:310
 FreshKillTrigger = <function> defined @WorldBossTimers/GUI.lua:185
 Hide = <function> defined @WorldBossTimers/GUI.lua:84
 btn_opts = <table> {
 }
 GetLabelText = <function> defined @WorldBossTimers/GUI.lua:153
 UpdateGUIVisibility = <function> defined @WorldBossTimers/GUI.lua:93
}
GUI = <table> {
 released = true
 Rebuild = <function> defined @WorldBossTimers/GUI.lua:169
 UpdateContent = <function> defined @WorldBossTimers/GUI.lua:214
 UpdateWidth = <function> defined @WorldBossTimers/GUI.lua:139
 CyclicLabelResetTrigger = <function> defined @WorldBossTimers/GUI.lua:199
 RemoveLabel = <function> defined @WorldBossTimers/GUI.lua:162
 Restart = <function> defined @WorldBossTimers/GUI.lua:45
 InitPosition = <function> defined @WorldBossTimers/GUI.lua:275
 Show = <function> defined @WorldBossTimers/GUI.lua:75
 UpdatePosition = <function> defined @WorldBossTimers/GUI.lua:259
 NewBasicWindow = <function> defined @WorldBossTimers/GUI.lua:322
 height = 106
 ShouldHide = <function> defined @WorldBossTimers/GUI.lua:65
 SetupAceGUI = <function> defined @WorldBossTimers/GUI.lua:306
 btn_req = <table> {
 }
 Update = <function> defined @WorldBossTimers/GUI.lua:248
 ShouldShow = <function> defined @WorldBossTimers/GUI.lua:53
 btn_container = <table> {
 }
 SaveGuiPoint = <function> defined @WorldBossTimers/GUI.lua:286
 CreateNewLabel = <function> defined @WorldBossTimers/GUI.lua:112
 CreateLabels = <function> defined @Interf

**Comment by fstenstrom** [comment] 2022-11-19 07:46
Thanks for reporting.

I couldn't reproduce it, but the reported nil access code looked problematic. Hopefully it's fixed by 240b080da2e615056581e35537a3a830899dcca0, which is now in latest version (v1.9.8). If you still see an issue, please re-open.

**Closed by fstenstrom** 2022-11-19 07:46 UTC
